"""aaa

Revision ID: dc701ffa76db
Revises: 
Create Date: 2024-05-22 11:00:40.860361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc701ffa76db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('partOfSpeech', sa.String(length=40), nullable=False),
    sa.Column('definition', sa.String(length=1000), nullable=False),
    sa.Column('synonyms', sa.String(length=100), nullable=True),
    sa.Column('example', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('surname', sa.String(length=140), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=140), nullable=False),
    sa.Column('photo', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
